name: Jekyll Themes
url: https://rakhil-1408.github.io
baseurl: /personal-blog
title: CloudOpsKube Blog
email: rakhilravindran007@gmail.com
author: Rakhil Ravindran

description: Insert tagline here

permalink: /themes/:title/

plugins: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
